on: push
name: 🚀 Deploy website
jobs:
  staging:
    name: 🎉 Staging
    runs-on: ubuntu-latest
    environment:
      name: STAGING
      url: https://uus.tori.ee/
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: ☕ Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: 🔨 Build Project
        run: |
          npm ci
          npm run build

      - name: ✍️ Create .env file
        run: |
          echo '${{ secrets.RECAPTCHA }}' > ./dist/.env
          echo '${{ vars.RECIPIENT }}' >> ./dist/.env

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          local-dir: ./dist/
          server: tori.ee
          username: staging.tori.ee
          password: ${{ secrets.PASSWORD }}
          protocol: ftps

  production:
    name: 🍾 Production
    runs-on: ubuntu-latest
    environment:
      name: PROD
      url: https://tori.ee/
    needs: [staging]
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: ☕ Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: 🔨 Build Project
        run: |
          npm ci
          npm run build

      - name: ✍️ Create .env file
        run: |
          echo '${{ secrets.RECAPTCHA }}' > ./dist/.env
          echo '${{ vars.RECIPIENT }}' >> ./dist/.env

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          local-dir: ./dist/
          server: tori.ee
          username: production.tori.ee
          password: ${{ secrets.PASSWORD }}
          protocol: ftps
